### ISSUE TITLE
Add the option for reload sql in runtime

### ISSUE THREAD

**Issue by josejuanmontiel** [zerodha/dungbeetle#20]
I think could be interesting use something like [fsnotify](https://github.com/fsnotify/fsnotify) to watch changes in sql file (when debugging or running outside the build... i need to try all the options) but the idea (later) is to have way to include new sql e.g. via API ... without restarting or in production...

**Comment by knadh** [comment]
Makes sense.
- A new `--watch` mode that auto-reloads.
- SIGHUP to send a reload signal to the app to reload everything.
