### ISSUE TITLE
Result table are not getting generated when I am using mysql

### ISSUE THREAD

**Issue by deepakpraka** [zerodha/dungbeetle#48]
I am using mysql as database and following my config file.

```

# Results database configuration (MySQL)
[results.my_results]
type = "mysql"  # Change this to MySQL
dsn = ""  # MySQL DSN for results
max_idle = 10
max_active = 100
connect_timeout = "10s"
results_table = "results_%s"

[db.my_db]
type = "mysql"  # Change this to MySQL
dsn = ""  # MySQL DSN for main database
max_idle = 10
max_active = 100
connect_timeout = "10s"

```

and when I am trying to get the job current state using following API:
`http://127.0.0.1:6060/jobs/e13
`
I am getting below error:
`
{"status":"success","data":{"job_id":"e13","state":"FAILURE","count":0,"error":"could not execute job : error writing columns to result backend: Error 1064 (42000): You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '\"results_e13\"' at line 1"}}
`

this is my db details:
```

Server: MySQL (127.0.0.1 via TCP/IP)
Server type: MySQL
Server connection: SSL is not being used Documentation
Server version: 8.0.31 - MySQL Community Server - GPL
Protocol version: 10
User: root@localhost
Server charset: UTF-8 Unicode (utf8mb4)

```

what I understood from the error code is that its not able to create a table.

is there anything I am missing?

**Comment by knadh** [comment]
hm, it could be that the MySQL result table generation broke at some point. Can you try a Postgres instance as your results DB and see if this recurs in your environment? If it works, then we know that there's a potential bug and can start debugging.

**Comment by deepakpraka** [comment]
I tried with postgress and it working as expected please find attached screenshots for more details so maybe there is some breaking changes for mysql.

![image](https://github.com/user-attachments/assets/967af209-3216-4bf4-83bf-93bc7ce87c98)


![image](https://github.com/user-attachments/assets/362bb908-6a5c-4c26-ab69-78f1bbf22dc9)
