### ISSUE TITLE
Cache database column types for SQL queries

### ISSUE THREAD

**Issue by MananGandhi1810** [zerodha/dungbeetle#51]
Since the queries are predefined, the output columns are also fixed. So, rather than computing them every time like [here](https://github.com/zerodha/dungbeetle/blob/6aaa016585a4e305136805cb5361574d3cab93e9/internal/resultbackends/sqldb/sqldb.go#L255), these can be stored on a cache, like Redis which is already being used for queuing.

**Comment by knadh** [comment]
It's indeed cached. That function is executed only once per task, and the results cached in a map: https://github.com/zerodha/dungbeetle/blob/6aaa016585a4e305136805cb5361574d3cab93e9/internal/resultbackends/sqldb/sqldb.go#L139

**Comment by MananGandhi1810** [comment]
Oh, my bad 😞
